---
title: "Data Visualization and Exploratory Data Analysis"
author: "Jessica Lavery"
date: "9/26/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

# Read in data from rnoaa package

```{r, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

# ggplot

## Basic scatterplot

```{r}
# via ggplot w/o pipe
ggplot(data = weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

# alternatively
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

# save plot as object
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()
class(plot_weather) # gg/ggplot
```

## Add colors

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```


